### ISSUE TITLE
Missing closing bracket in class declaration

### ISSUE THREAD

**Issue by nerudaj** [Hapaxia/SfmlTextAline#1]
https://github.com/Hapaxia/SfmlTextAline/blob/a5a316470b48e034ee2baa584d2b65e35b1c6cd8/SfmlTextAline/SfmlTextAline.hpp#L108

class isn't closed with `};`, code doesn't compile.

**Comment by Hapaxia** [comment]
Ouch! My bad. I removed some notes I have there during commit and must have gone too far and took an extra line or two.
Thanks for spotting it. I'll fix right away!
