### ISSUE TITLE
Add Justification Alignment

### ISSUE THREAD

**Issue by Hapaxia** [Hapaxia/SfmlTextAline#4]
Add option to allow the use of justification.

Whether a line's whitespace would be stretched by word, by space, by either or by a controlled mixture of both can still be considered.

**Comment by Hapaxia** [comment]
Justification now added for character spreading/distribution.

Justification by spreading only whitespace is still needed though. This will take more work: it needs to know where whitespace is when spreading so can't just use the quads (as whitespace produces no quads). Looks like I'll have to re-implement an earlier idea where the Line tracks the actual text used for that line (string index start and number of characters).

**Comment by nerudaj** [comment]
> Justification now added for character spreading/distribution.
> 
> Justification by spreading only whitespace is still needed though. This will take more work: it needs to know where whitespace is when spreading so can't just use the quads (as whitespace produces no quads). Looks like I'll have to re-implement an earlier idea where the Line tracks the actual text used for that line (string index start and number of characters).

A tip - if you don't know a std::string_view, take a look at it. Internally it just holds a pointer to the start of the string and the length of that string, so it is a zero overhead when compared to normal string.

**Comment by Hapaxia** [comment]
Indeed.

The entire text is just one string though so I was tracking the index of the beginning of each line as well as the length of each so each line knows which part of the string it uses. I'll need that again, I think.
Basically, I mean that the characters needed for each line is a substring inside the actual one so it would just track where characters it would be using.

There shouldn't be any copying of strings; just accessing each character directly.

**Comment by Hapaxia** [comment]
fixed in 7855ee7

Justification can now spread only whitespace or characters (as well as whitespace) to suit preference.
