### ISSUE TITLE
Syntax error: stray/leftover comment-close

### ISSUE THREAD

**Issue by xparq** [Hapaxia/SfmlTextAline#6]
Dear Maestro! If I'm correct, there's a syntax error (a stray comment-closing `*/`) introduced in fb9039ea (0.2) in the header.
I've created a change request (#5) for it (sorry, I'm kinda reluctant to call it "pull request" :) ), basically to practice it (I'm not a fervent collaborator, you see), but you may prefer issues instead, so here.

(The interesting puzzle to me, however, is this: I have a mild case of ADD, so things like this are especially familiar and perfectly normal to me, and I'd have never even noticed it, only the compiler did. But how did this survive not one, but two (nontrivial) commits with your setup? And then add #1 to the plot. I mean you must have run it somehow, I guess. Please, I can't sleep until this mystery is solved! :)Thx!)

**Comment by Hapaxia** [comment]
Hi!

Thank you for your interest and I really appreciate you noticing this.

First, I'll just say that it should be fixed presently.

Secondly, I'll explain why it's happening (and maybe multiple times!).
I have a comment in the code that I'm using as reference to make sure I'm following a plan and not adding or removing stuff I should not; it's something I need - for now. When I make a commit, I remove the lines from the commit - not the actual file - and I may sometimes miss which exact lines to commit or not.
I hope this satisfies your question and soothes the mystery-solving part of your brain so you can sleep better! :)

**Comment by Hapaxia** [comment]
fixed in cf94d68

**Comment by xparq** [comment]
Hehh, thanks for the explanation, now I can finally go to bed. :)

_(I have another change in my fork that you might be interested in, but then I'm not gonna submit another PR, as it seems you have similar aversions against accepting them as I do, but will add another issue soon.)_
